### ISSUE TITLE
Output Error while generating large number of fine slices

### ISSUE THREAD

**Issue by srikanth1986** [heitzmann/gdspy#36]
I need to make fine slices of the polygons for my application and I wrote a script for the same. While the script itself doesn't throw any error, I see that polygons generated after slice operation are shifted from the original in a specific pattern. Here is original polygons superimposed.

![image](https://user-images.githubusercontent.com/2020325/34409453-e8926c94-ebef-11e7-9752-7b396b768c7c.png)

The slices are aligned with the original in the left and right edges, but shifted down in the middle of the polygon. The deviation is more prominent when the slice is finer.
Here is the same output zoomed in with original polygon highlighted in white.

![image](https://user-images.githubusercontent.com/2020325/34409511-35c6118c-ebf0-11e7-90b6-4b825cb19919.png)

And here is one of the slices highlighted in white.

![image](https://user-images.githubusercontent.com/2020325/34409540-5d6c51d8-ebf0-11e7-81bf-32df110f5130.png)

This is the code that generates this result.
`#!/usr/bin/python
import numpy 
import gdspy

def frange(start, stop, step):
        i = start
        while i < stop:
	        yield i
	        i += step

poly_cell = gdspy.Cell('POLYGONS')
points = [(10.43631016, -35.44995495), (20.43478711, -35.27543088), (20.41733471, -34.27558319), (10.41885775, -34.45010725)]

polylist = []

poly2 = gdspy.Polygon(points, 0)
poly_cell.add(poly2)
polylist.append(poly2)

bbox = poly_cell.get_bounding_box()
print (bbox)
sl = []

for i in frange(bbox[0][0]+0.005, bbox[1][0]+0.005, .01):
        sl.append(i)

result = gdspy.slice(polylist, (sl), 0)
poly_cell.add(result)
gdspy.LayoutViewer()
`

**Comment by heitzmann** [comment]
Which version of gdspy are you using? I'm guessing 1.2 or latter, because this looks like a precision error.
`slice` has a keyword argument `precision` that is set to 0.001 by default, which means all polygon vertices are aligned to a grid with 1e-3 spacing.

Try to run with:
```python
result = gdspy.slice(polylist, (sl), 0, precision=1e-6)
```
to see if that solves the problem.

**Comment by srikanth1986** [comment]
Yes, That fixes it. I wasn't sure what the precision parameter was for.
Maybe you can add that to the description here
http://gdspy.readthedocs.io/en/latest/geometry.html#slice
And thanks for the super quick reply!

**Comment by heitzmann** [comment]
Thanks! I missed that in the docs! Fixed in 5ca48f0.

**Comment by srikanth1986** [comment]
Although this has fixed the problem for me, I do have some concern about
this solution. One, I was slicing at 0.01 intervals while the default
precision was 0.001. The second being that, what you say should have
resulted in an abrupt shift like a step function, but if you look at the
right half of the images, the slices catch up with original in a rather
smooth curve. Also I noticed the same thing happening in rectangles half as
long as this where the slices at the left and right are aligned while those
in the middle are not. Grid snapping doesn't explain this in my opinion.

**Comment by heitzmann** [comment]
Indeed... that is an artifact of the combined effects of the grid snapping and the way slicing is performed: from left to right, one slice at a time.
To solve the issue I believe the `_chop` function in the C-extension should perform all chops (from the list of `positions` in a single run).
I'll reopen the issue until this can be implemented.

**Comment by heitzmann** [comment]
@srikanth1986 I believe changes in https://github.com/heitzmann/gdspy/commit/9a951ae8939bfb8acb7d20efa6e9e5c6437aa5b1 solve this issue. I've tested your example and it works as expected for any precision setting.
Please let me know if you find any other issue.

**Comment by srikanth1986** [comment]
Hi Lucas, How do I get this update for python on windows? I tried both
pip install --upgrade gdspy
and then downloaded the files and ran
python setup.py install

I still see the old output.

**Comment by heitzmann** [comment]
@srikanth1986 You can get the latest Windows builds from AppVeyor: https://ci.appveyor.com/project/heitzmann/gdspy
Just select the environment corresponding to your python version and platform, then go to the Artifacts tab and download the whl file.

**Comment by srikanth1986** [comment]
That works. Thank you very much!

On Tue, Jan 2, 2018 at 3:36 PM, Lucas H. Gabrielli <notifications@github.com
